// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VsctCompletion
{
    internal sealed partial class Vsix
    {
        public const string Id = "7DF4A810-9DDD-4AFB-A4A0-D2C6D6C0DCA2";
        public const string Name = "C# Documentation Completion";
        public const string Description = @"Additional Intellisense completion items for C# XML comments";
        public const string Language = "en-US";
        public const string Version = "1.0.0";
        public const string Author = "Daniel Kopp";
        public const string Tags = "xml, comment, cs";
    }
}
